#Expyriment 1.0.0 (Python 3.11.2), .xpe-file, coding: UTF-8
#date: Wed Sep 24 2025 12:02:02
#sha1: d6b15b
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='anna', release='6.1.0-37-amd64', version='#1 SMP PREEMPT_DYNAMIC Debian 6.1.140-1 (2025-05-22)', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
570,design,log,
#design: #exp: Two Squares
#design: block_cnt,block_id,trial_cnt,trial_id
570,design,logged,
570,Experiment,started
571,Stimulus,presented,1
592,Stimulus,presented,0
592,stderr,received,'Traceback (most recent call last):'
592,stderr,received,'  File "/home/anna/ENS/3A/cogsup/exp_app/PPE/Week-2/Exercises/two_squares.py", line 33, in <module>'
593,stderr,received,'    line_1.plot(bl)'
593,stderr,received,'                ^^'
593,stderr,received,"NameError: name 'bl' is not defined"
